/**
 * Created by Mita on 30.1.2018..
 */

/**SPLASH ACTIONS**/
export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_ERROR = 'FETCHING_DATA_ERROR';
export const OPEN_NEXT_SCREEN = 'OPEN_NEXT_SCREEN';

/**LIST_PRODUCTS ACTIONS**/
export const OPEN_SINGLE_PRODUCT = 'OPEN_SINGLE_PRODUCT';

/**SINGLE_PRODUCT ACTIONS**/
export const OPEN_MODAL_IMAGE = 'OPEN_MODAL_IMAGE';
export const CLOSE_MODAL_IMAGE = 'CLOSE_MODAL_IMAGE';

/**COMMENTS ACTIONS**/
export const OPEN_MODAL_ADD_COMMENT = 'OPEN_MODAL_ADD_COMMENT';
export const CLOSE_MODAL_ADD_COMMENT = 'CLOSE_MODAL_ADD_COMMENT';
export const SAVE_COMMENT = 'SAVE_COMMENT';
export const SET_TEXT = 'SET_TEXT';